<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

do_action( 'genesis_doctype' );
do_action( 'genesis_title' );
do_action( 'genesis_meta' );

wp_head(); // We need this for plugins.
?>

</head>

<?php
remove_action( 'genesis_header', 'genesis_do_header' );
add_action( 'genesis_header', 'boofilltech_header_theme' );


genesis_markup( array(
    'open'   => '<body %s>',
    'context' => 'body',
) );
do_action( 'genesis_before' );

genesis_markup( array(
    'open'   => '<div %s>',
    'context' => 'site-container',
) );

do_action( 'genesis_header' );

genesis_markup( array(
    'open'   => '<div %s>',
    'context' => 'site-inner',
) );
genesis_structural_wrap( 'site-inner' );

function boofilltech_header_theme(){

    ?>
    <div class="logoContainer">
        <a aria-label="Click to go to homepage" href="<?php echo get_home_url(); ?>">
            <img alt="" src="<?php echo esc_url(get_local_image('rio-border-cafe.png')); ?>" />
        </a>
    </div>
    <div class="navContainer">
        <div id="nav-holder">
            <?php genesis_nav_menu( array( 'theme_location' => 'primary', 'menu_class' => '', 'container' => 'primary-nav', )); ?>
            <button id="close-menu" aria-label="Close Menu Navigation" onclick="toggleNav()"></button>
        </div>
    </div>
    <button id="open-menu" aria-label="Open Menu Navigation" onclick="toggleNav()">
        <img src="data:image/webp;base64,UklGRuoAAABXRUJQVlA4TN0AAAAv/8F/EA8w/vM///Mf8HBU27bTPCBlGAlIiTSQhhQkMEzvs53eXkT/GbltG0k+tTNz62IgnjwguNJ/nkJ2e6gmIro9VRWxsNQXYzzcY0WrKTpN1Wumg2a20NSejWbu2Wkaz/7jp9s/d27/3L39e8ffm/7e9r7B+xbvm2KDl533jd63et/Mlf6Tw9Hqsn8MOPbg6/4+d/kE5CZ97vLx5yY/v7lLf+48f7lLf28+/twl/+/E+z7vO6/A93Kl/+RwbGjZ/A70jfR1/z9AfSN57vIKfGP0+Mub7xuZ/vMKEAA=" alt="Navigation" width="32" height="32" />
    </button>

<?php }
